/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    NDataTable: typeof import('naive-ui')['NDataTable']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    Pdf: typeof import('./src/components/pdf.vue')['default']
  }
}
